name: Build Components V2
# name: ''

on:
  push:
  pull_request:
    branches:
      - main

run-name: ${{ inputs.run_name }}

jobs:
  promote_version:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
    # if: 1 == 1
    if: ${{ always() }}
